name: 'Slack Notify'
description: 'Post a slack message'
inputs:
  webhook_url:
    description: 'The webhook URL including the hooks.slack.com part'
    required: true
  message:
    description: "Additional information passed on"
runs:
  using: composite
  steps:
    - name: Notify Success
      if: success()
      shell: bash
      run: |
        curl ${{ inputs.webhook_url }} -v -H "Content-Type: application/json" -d '{"text": "Deploy to ${{ github.repository}} succeeded.", "blocks":[{"type":"section","text":{"type":"mrkdwn","text":"*Deploy to ${{ github.repository}} succeeded.*"}},{"type":"section","fields":[{"type":"mrkdwn","text":"*Run:* <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|Logs>"},{"type":"mrkdwn","text":"*Status*: succeeded"},{"type":"mrkdwn","text":"*Actor*: ${{ github.actor }}"},{"type":"mrkdwn","text":"*Event*: ${{ github.event_name }}"}]},{"type":"divider"},{"type":"section","text":{"type":"mrkdwn","text":"${{ inputs.message }}"}}]}'

    - name: Notify Failure
      if: failure()
      shell: bash
      run: |
        curl ${{ inputs.webhook_url }} -v -H "Content-Type: application/json" -d '{"text": "Deploy to ${{ github.repository}} failed.", "blocks":[{"type":"section","text":{"type":"mrkdwn","text":"*Deploy to ${{ github.repository}} failed.*"}},{"type":"section","fields":[{"type":"mrkdwn","text":"*Run:* <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|Logs>"},{"type":"mrkdwn","text":"*Status*: succeeded"},{"type":"mrkdwn","text":"*Actor*: ${{ github.actor }}"},{"type":"mrkdwn","text":"*Event*: ${{ github.event_name }}"}]},{"type":"divider"},{"type":"section","text":{"type":"mrkdwn","text":"${{ inputs.message }}"}}]}'

    - name: Notify Cancelled
      if: cancelled()
      shell: bash
      run: |
        curl ${{ inputs.webhook_url }} -v -H "Content-Type: application/json" -d '{"text": "Deploy to ${{ github.repository}} cancelled. ", "blocks":[{"type":"section","text":{"type":"mrkdwn","text":"*Deploy to ${{ github.repository}} cancelled.*"}},{"type":"section","fields":[{"type":"mrkdwn","text":"*Run:* <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|Logs>"},{"type":"mrkdwn","text":"*Status*: succeeded"},{"type":"mrkdwn","text":"*Actor*: ${{ github.actor }}"},{"type":"mrkdwn","text":"*Event*: ${{ github.event_name }}"}]},{"type":"divider"},{"type":"section","text":{"type":"mrkdwn","text":"${{ inputs.message }}"}}]}'
