name: 'Slack Notify'
description: 'Post a slack message'
inputs:
  workflow_name:
    description: The name of the workflow that called this action
    required: true
  webhook_url:
    description: 'The webhook URL including the hooks.slack.com part'
    required: true
  message:
    description: "Additional information passed on"
  status:
    description: Overall status
    required: true
runs:
  using: composite
  steps:
    - name: Notify Success
      shell: bash
      run: |
        curl ${{ inputs.webhook_url }} -v -H "Content-Type: application/json" -d '{"text": "Action: ${{ inputs.workflow_name }} in ${{ github.repository}} ${{ inputs.status }}.", "blocks":[{"type":"section","text":{"type":"mrkdwn","text":"*Action: ${{ inputs.workflow_name }} in ${{ github.repository}} ${{ inputs.status }}.*"}},{"type":"section","fields":[{"type":"mrkdwn","text":"*Run:* <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|Logs>"},{"type":"mrkdwn","text":"*Status*: succeeded"},{"type":"mrkdwn","text":"*Actor*: ${{ github.actor }}"},{"type":"mrkdwn","text":"*Event*: ${{ github.event_name }}"}]},{"type":"divider"},{"type":"section","text":{"type":"mrkdwn","text":"${{ inputs.message }}"}}]}'